### ISSUE TITLE
gpu_setting

### ISSUE THREAD

**Issue by yyeennyy** [yyeennyy/VisualRadio#138]
# Motivation
gpu 사용을 위한 docker-compose.yaml 세팅

# How to
**docker-compose.yaml 수정**
우리의 visual-radio 서비스 하위에 gpu 설정을 추가합니다. 
그럼 간단히 gpu 설정이 가능합니다. nvidia-smi가 잘 잡힙니다.
물론 컨테이너에서 cuda 설치와 cudnn 설치는 진행해야 했습니다. 

```
  deploy:
    resources:
      reservations:
        devices:
        - driver: nvidia
          count: 1
          capabilities: [gpu]
```

**tensorflow버전 변경**
기존: 2.13
변경: 2.11
=> 우리가 사용할 cuda와 cudnn 버전에 호환되는 tensorflow 버전으로 변경했습니다.
- cuda-11.2.2
- cudnn 8.1.1
- tensorflow 2.11
버전 호환성은 아래 링크에서 확인 가능합니다.
https://www.tensorflow.org/install/source#install_gpu_support_optional_linux_only﻿
